apiVersion: v2
name: cluster-overprovisioner
description: Helm chart, that enables scheduled scaling of a target resource, intended to be add overprovisioning to an autoscaling k8s cluster.
type: application
version: 0.8.1
appVersion: "1.8.9"
keywords:
  - cluster-autoscaler
  - overprovisioning
  - cluster-proportional-autoscaler
  - scheduled-overprovisioning
  - cpa
maintainers:
  - name: tielou
    email: thilo@wobker.co
  - name: grieshaber
    email: freddy.grieshaber+github@gmail.com
